name: Release Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manuel tetikleyici

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Print current path
      run: pwd
      
    - name: Build and push backend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ../../react-express-mongodb/backend
        push: true
        tags: ugurcan653/react-express-mongodb-backend:latest
      
    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ../../react-express-mongodb/frontend
        push: true
        tags: ugurcan653/react-express-mongodb-frontend:latest
